theme: almeida-cv
baseURL: https://resume.dereksrose.com/
languageCode: en-us
DefaultContentLanguage: en
title: "Derek Rose - You'll Like Him"
googleAnalytics: UA-153109937-1
summarylength: 10
enableEmoji: true
enableRobotsTXT: true

params:
  colorDark: "#666"
  colorLight: "#fff"
  colorPageBackground: "#ddd"
  colorPrimary: "#e3bfb8"
  colorPrimaryText: "#fff"
  colorRightColumnBackground: "#f5f5f5"
  colorSecondary: "#aaa"
  pages: 3